version: '3.7'
services:
    postgres:
        container_name: postgres_docker
        image: postgres
        restart: always
        environment:
            "POSTGRES_PASSWORD": "postgres"
            "POSTGRES_USER": "postgres"
            "POSTGRES_DB": "sampledb"
        ports:
            - '5432-5435:5432-5435'
        volumes:
            - ./postgres/postgres:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    mongodb_container:
        container_name: mongodb_docker
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_DATABASE: sampledb
            MONGO_INITDB_ROOT_USERNAME: sample
            MONGO_INITDB_ROOT_PASSWORD: samplepassword
        ports:
            - '27017-27019:27017-27019'
        volumes:
            - ./mongodb_data_container:/data/db
            - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            
volumes:
    mongodb_data_container:
